/**
 * lib/export-serializer.ts
 * Serializes ReviewResponse object into Markdown and JSON export text payloads.
 */

import type { ReviewResponse } from "@/types/review";

/**
 * Converts a ReviewResponse into a clean, formatted Markdown document.
 */
export function generateMarkdownReport(review: ReviewResponse): string {
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let md = `# Architecture Review Report: ${review.architectureTitle}\n\n`;
  md += `**Date:** ${dateStr}  \n`;
  md += `**Vision Score:** ${review.confidenceScore}%  \n\n`;
  md += `## Executive Summary\n${review.summary}\n\n`;

  if (review.ambiguities && review.ambiguities.length > 0) {
    md += `### Ambiguous Diagram Elements\n`;
    review.ambiguities.forEach((amb) => {
      md += `- ⚠️ ${amb}\n`;
    });
    md += `\n`;
  }

  // Categories
  const { scalability, reliability, bottlenecks, designTradeoffs } = review.categories;

  if (scalability.length > 0) {
    md += `## 🚀 Scalability Analysis\n`;
    scalability.forEach((item) => {
      md += `### [${item.severity.toUpperCase()}] ${item.title}\n`;
      md += `${item.explanation}\n\n`;
      if (item.recommendation) {
        md += `**Recommendation:** ${item.recommendation}\n\n`;
      }
    });
  }

  if (reliability.length > 0) {
    md += `## 🛡️ Reliability & Redundancy\n`;
    reliability.forEach((item) => {
      md += `### [${item.severity.toUpperCase()}] ${item.title}\n`;
      md += `${item.explanation}\n\n`;
      if (item.recommendation) {
        md += `**Recommendation:** ${item.recommendation}\n\n`;
      }
    });
  }

  if (bottlenecks.length > 0) {
    md += `## ⏳ Performance Bottlenecks\n`;
    bottlenecks.forEach((item) => {
      md += `### [${item.severity.toUpperCase()}] ${item.title}\n`;
      md += `${item.explanation}\n\n`;
      if (item.recommendation) {
        md += `**Recommendation:** ${item.recommendation}\n\n`;
      }
    });
  }

  if (designTradeoffs.length > 0) {
    md += `## ⚖️ Design Trade-offs\n`;
    designTradeoffs.forEach((trade) => {
      md += `### ${trade.title}\n`;
      md += `${trade.explanation}\n`;
      md += `- **Benefit:** ${trade.benefit}\n`;
      md += `- **Cost:** ${trade.cost}\n\n`;
    });
  }

  if (review.mermaidDiagram) {
    md += `## 📊 Reconstructed Mermaid.js Diagram\n\n\`\`\`mermaid\n${review.mermaidDiagram}\n\`\`\`\n`;
  }

  md += `\n---\n*Report generated by AI System Design Reviewer (ArchCheck)*\n`;
  return md;
}

/**
 * Triggers a client-side file download for string content.
 */
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
