/**
 * lib/iac-generator.ts
 * Generates Terraform, Docker Compose, and CloudFormation IaC files from a ReviewResponse.
 */

import type { ReviewResponse } from "@/types/review";
import type { IaCGenerationResult, IaCFile } from "@/types/iac";

/**
 * Generates ready-to-deploy IaC files that match the reviewed architecture.
 */
export function generateIaC(
  review: ReviewResponse,
  provider: "aws" | "gcp" | "azure" = "aws"
): IaCGenerationResult {
  const safeTitle = review.architectureTitle.toLowerCase().replace(/[^a-z0-9]/g, "_").slice(0, 30);

  const terraform: IaCFile = {
    filename: "main.tf",
    format: "terraform",
    language: "hcl",
    description: "Terraform root module — provisions ECS cluster, RDS PostgreSQL, ElastiCache Redis, and SQS queue.",
    content: `# ArchCheck Generated Terraform — ${review.architectureTitle}
# Provider: ${provider.toUpperCase()} | Generated by AI System Design Reviewer

terraform {
  required_version = ">= 1.7.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region"   { default = "us-east-1" }
variable "app_name"     { default = "${safeTitle}" }
variable "environment"  { default = "production" }

# ── VPC & Networking ───────────────────────────────────────────
resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  tags = { Name = "\${var.app_name}-vpc" }
}

resource "aws_subnet" "private" {
  count             = 2
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.\${count.index}.0/24"
  availability_zone = data.aws_availability_zones.available.names[count.index]
  tags = { Name = "\${var.app_name}-private-\${count.index}" }
}

data "aws_availability_zones" "available" {}

# ── ECS Cluster ────────────────────────────────────────────────
resource "aws_ecs_cluster" "app" {
  name = "\${var.app_name}-cluster"

  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}

# ── RDS PostgreSQL ─────────────────────────────────────────────
resource "aws_db_instance" "postgres" {
  identifier        = "\${var.app_name}-db"
  engine            = "postgres"
  engine_version    = "15.4"
  instance_class    = "db.t3.medium"
  allocated_storage = 100
  storage_encrypted = true
  multi_az          = true

  db_name  = replace(var.app_name, "-", "_")
  username = "admin"
  password = var.db_password

  skip_final_snapshot = false
  final_snapshot_identifier = "\${var.app_name}-final-snapshot"

  tags = { Name = "\${var.app_name}-postgres" }
}

variable "db_password" {
  description = "RDS PostgreSQL master password"
  sensitive   = true
}

# ── ElastiCache Redis Cluster ──────────────────────────────────
resource "aws_elasticache_cluster" "redis" {
  cluster_id           = "\${var.app_name}-redis"
  engine               = "redis"
  node_type            = "cache.t3.medium"
  num_cache_nodes      = 1
  parameter_group_name = "default.redis7"
  port                 = 6379
}

# ── SQS Dead-Letter Queue ──────────────────────────────────────
resource "aws_sqs_queue" "dlq" {
  name                       = "\${var.app_name}-dlq"
  message_retention_seconds  = 1209600  # 14 days
}

resource "aws_sqs_queue" "main" {
  name                      = "\${var.app_name}-queue"
  visibility_timeout_seconds = 30

  redrive_policy = jsonencode({
    deadLetterTargetArn = aws_sqs_queue.dlq.arn
    maxReceiveCount     = 5
  })
}

# ── Outputs ─────────────────────────────────────────────────────
output "ecs_cluster_arn"  { value = aws_ecs_cluster.app.arn }
output "rds_endpoint"     { value = aws_db_instance.postgres.endpoint }
output "redis_endpoint"   { value = aws_elasticache_cluster.redis.cache_nodes[0].address }
output "sqs_queue_url"    { value = aws_sqs_queue.main.id }
`,
  };

  const dockerCompose: IaCFile = {
    filename: "docker-compose.yml",
    format: "docker-compose",
    language: "yaml",
    description: "Docker Compose stack for local development — API server, PostgreSQL, Redis, and queue worker.",
    content: `# ArchCheck Docker Compose — ${review.architectureTitle}
# Generated by AI System Design Reviewer

version: "3.9"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/app_db
      - REDIS_URL=redis://cache:6379
      - SQS_ENDPOINT=http://localstack:4566
    depends_on:
      - db
      - cache
    restart: unless-stopped
    networks:
      - app-network

  worker:
    build: .
    command: npm run worker
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/app_db
      - REDIS_URL=redis://cache:6379
    depends_on:
      - db
      - cache
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - app-network

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
`,
  };

  const cloudFormation: IaCFile = {
    filename: "cloudformation.json",
    format: "cloudformation",
    language: "json",
    description: "AWS CloudFormation template — S3 artifact bucket, ECS task definition, and SQS queue.",
    content: JSON.stringify(
      {
        AWSTemplateFormatVersion: "2010-09-09",
        Description: `ArchCheck — ${review.architectureTitle} CloudFormation Stack`,
        Parameters: {
          Environment: { Type: "String", Default: "production", AllowedValues: ["development", "staging", "production"] },
          AppName: { Type: "String", Default: safeTitle },
        },
        Resources: {
          ArtifactBucket: {
            Type: "AWS::S3::Bucket",
            Properties: {
              BucketName: { "Fn::Sub": "${AppName}-artifacts-${AWS::AccountId}" },
              VersioningConfiguration: { Status: "Enabled" },
              BucketEncryption: {
                ServerSideEncryptionConfiguration: [
                  { ServerSideEncryptionByDefault: { SSEAlgorithm: "aws:kms" } },
                ],
              },
            },
          },
          AppSQSQueue: {
            Type: "AWS::SQS::Queue",
            Properties: {
              QueueName: { "Fn::Sub": "${AppName}-queue" },
              VisibilityTimeout: 30,
              RedrivePolicy: {
                deadLetterTargetArn: { "Fn::GetAtt": ["DeadLetterQueue", "Arn"] },
                maxReceiveCount: 5,
              },
            },
          },
          DeadLetterQueue: {
            Type: "AWS::SQS::Queue",
            Properties: {
              QueueName: { "Fn::Sub": "${AppName}-dlq" },
              MessageRetentionPeriod: 1209600,
            },
          },
        },
        Outputs: {
          S3BucketName: { Value: { Ref: "ArtifactBucket" } },
          SQSQueueURL: { Value: { Ref: "AppSQSQueue" } },
        },
      },
      null,
      2
    ),
  };

  return {
    architectureTitle: review.architectureTitle,
    provider,
    files: [terraform, dockerCompose, cloudFormation],
    deploymentNotes: [
      "Run `terraform init && terraform plan` before applying to validate the infrastructure plan.",
      "Set DB_PASSWORD as a Terraform secret via `export TF_VAR_db_password=...` before `terraform apply`.",
      "Use `docker compose up --build` for local development with hot-reloading.",
      "The CloudFormation template deploys to the AWS region specified in your CLI profile.",
    ],
  };
}
